# Markowitz Model Performance

In [2]:
import numpy as np

In [3]:


matrix = np.matrix([
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5]
])

print(np.cov(matrix))

[[2.5 2.5 2.5 2.5]
 [2.5 2.5 2.5 2.5]
 [2.5 2.5 2.5 2.5]
 [2.5 2.5 2.5 2.5]]
