# Markowitz Model Performance

In [3]:
import numpy as np

In [11]:


matrix = np.matrix([
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5]
])

print(matrix[:, 2:5])
print(np.mean(matrix[:, 2:5]))

[[3 4 5]
 [3 4 5]
 [3 4 5]
 [3 4 5]]
4.0
